basic_settings:
  site_title: Populi
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/populi-lockup.svg
  logo_width: 140

menu_settings:
  menu_items:
    - title: ''
      url: '/'
    - title: 'Features'
      url: '/features'
    - title: 'For Everyone'
      url: '/for-everyone'
    - title: 'Customers'
      url: '/customers'
    - title: 'Pricing'
      url: '/pricing'
    - title: 'Get a Demo'
      url: '/get-a-demo'
      button: true

footer_settings:
  logo_image: /images/populi-mark.svg
  logo_width: 36

grid_settings:
  overlay_opacity: 1
  grid_spacing: 16

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

authors: 
  brendan: 
    display_name: Brendan
    email: brendan@populi.co
    first_name: Brendan
    last_name: O'Donnell
    profile_image_class: brendan
  adam: 
    display_name: Adam
    email: adam@populi.co
    first_name: Adam
    last_name: Sentz
    profile_image_class: adam
  isaac:
    display_name: Isaac
    email: isaac@populiweb.com    
    first_name: Isaac
    last_name: Grauke
    profile_image_class: isaac
  mark:
    display_name: Mark
    email: mark@populi.co
    first_name: Mark
    last_name: Ackerman
    profile_image_class: mark
  james:
    display_name: James
    email: james@populi.co    
    first_name: James
    last_name: Hill
    profile_image_class: james
  josh:
    display_name: Josh
    email: josh@populi.co    
    first_name: Josh
    last_name: Stevenson
    profile_image_class: josh
  matt:
    display_name: Matt
    email: matt@populi.co
    first_name: Matt
    last_name: Jepsen
    profile_image_class: matt
  patrick:
    display_name: Patrick
    email: patrick@populiweb.com    
    first_name: Patrick
    last_name: Swanson
    profile_image_class: patrick

social_settings:
  facebook_url: 'https://www.facebook.com/populico'
  twitter_url: 'https://twitter.com/Populi'
  instagram_url: 'https://www.instagram.com/populico/'
  snapchat_url: ''
  youtube_url: 'https://youtube.com/c/populico'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/company/populi/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F9F7F1'
  text_dark_color: '#1B2B36'
  text_medium_color: '#49555E'
  text_light_color: '#BBBFC3'
  accent_color: '#4EC4FF'
  border_color: '#E8EAEB'
  overlay_background_color: '#1B2B36'
  overlay_text_color: '#F9F7F1'
  overlay_accent_color: '#4EC4FF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">'
  title_font: '"Messina Serif", serif'
  body_font: '"DM Sans", sans-serif'
  regular_weight: 400
  bold_weight: 600

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

about:
- title: Vision
  url: index
- title: Web Based, Hosted
  url: web-based-hosted
- title: Support
  url: support
- title: Security
  url: security
- title: Implementation
  url: implementation

legal:
 - {title: "Terms of Service", page: terms}
 - {title: "Acceptable Use Policy", page: aup}
 - {title: "Privacy Policy", page: privacy}
 - {title: "Copyright Policy", page: copyright}