basic_settings:
  site_title: Populi
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/populi-lockup.svg
  logo_width: 140

menu_settings:
  menu_items:
    - title: ''
      url: '/'
    - title: 'Features'
      url: '/features'
    - title: 'For Everyone'
      url: '/for-everyone'
    - title: 'Customers'
      url: '/customers'
    - title: 'Get a Demo'
      url: '/get-a-demo'
      button: true

footer_settings:
  logo_image: /images/populi-mark.svg
  logo_width: 36

grid_settings:
  overlay_opacity: 1
  grid_spacing: 16

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/populico'
  twitter_url: 'https://twitter.com/Populi'
  instagram_url: 'https://www.instagram.com/populico/'
  snapchat_url: ''
  youtube_url: 'https://youtube.com/c/populico'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/company/populi/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F9F7F1'
  text_dark_color: '#1B2B36'
  text_medium_color: '#49555E'
  text_light_color: '#BBBFC3'
  accent_color: '#4EC4FF'
  border_color: '#E8EAEB'
  overlay_background_color: '#1B2B36'
  overlay_text_color: '#F9F7F1'
  overlay_accent_color: '#4EC4FF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Messina Serif", serif'
  body_font: '"DM Sans", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 24
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: -0.02
  menu:
    small_size: 32
    medium_size: 16
    large_size: 18
    weight: 400
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 56
    medium_size: 80
    large_size: 104
    weight: 600
    letter_spacing: -0.02
    line_height: 0.94
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

features:
- title: Recruit
  url: recruit
- title: Admit
  url: admit
- title: Teach
  url: teach
- title: Administer
  url: administer
- title: Aid
  url: aid
- title: Account
  url: account
- title: Advance
  url: advance


about:
 - {title: "Our Vision", page: index}
 - {title: "Web-based, Hosted", page: webbasedhosted}
 - {title: Support, page: support}
 - {title: Security, page: security}
 - {title: Implementation, page: implementation}

legal:
 - {title: "Terms of Service", page: terms}
 - {title: "Acceptable Use Policy", page: aup}
 - {title: "Privacy Policy", page: privacy}
 - {title: "Copyright Policy", page: copyright}